import { FindOptionsRelations, FindOptionsSelect } from "typeorm";
import { BaseSelect, RelationSelectConfig } from "@/shared/base/BaseSelect";
import { Order } from "@/database/models/store/Order";

export const OrderSelectList: FindOptionsSelect<Order> = {
  ...BaseSelect,
  storeId: true,
  type: true,
  status: true,
  code: true,
  orderAt: true,
  occurredAt: true,
  canceledAt: true,
  partnerId: true,
  partnerSnapshot: true,
  completerId: true,
  completerSnapshot: true,
  cancelerId: true,
  cancelerSnapshot: true,
  shipperId: true,
  shipperSnapshot: true,
  discountType: true,
  discountValue: true,
  taxType: true,
  taxValue: true,
  shippingFee: true,
  isFreeShipping: true,
  grossAmount: true,
  discountAmount: true,
  netAmount: true,
  taxAmount: true,
  totalAmount: true,
  totalCost: true,
  refOrderId: true,
  returnDiscountType: true,
  returnDiscountValue: true,
  returnTaxType: true,
  returnTaxValue: true,
  returnGrossAmount: true,
  returnDiscountAmount: true,
  returnNetAmount: true,
  returnTaxAmount: true,
  returnTotalAmount: true,
  returnTotalCost: true,
  settlementAmount: true,
  lines: true,
  returnLines: true,
  incomeExpenses: true,
  partner: { id: true, type: true, name: true, code: true, phone: true, taxCode: true },
  shipper: { id: true, type: true, name: true, code: true, phone: true },
} as any;

export const OrderSelectFull: FindOptionsSelect<Order> = {
  ...OrderSelectList,
  partner: true,
  completer: true,
  canceler: true,
  shipper: true,
  refOrder: {
    id: true,
    storeId: true,
    type: true,
    status: true,
    code: true,
    orderAt: true,
    partnerId: true,
    partnerSnapshot: true,
  },
  lines: {
    id: true,
    orderId: true,
    returnOrderId: true,
    refOrderLineId: true,
    productId: true,
    productSnapshot: true,
    unitId: true,
    unitSnapshot: true,
    conversionRateAtTime: true,
    unitPrice: true,
    quantity: true,
    subTotal: true,
    totalCost: true,
    costPriceAtTime: true,
    product: {
      id: true,
      code: true,
      name: true,
      baseUnitId: true,
      baseUnit: { id: true, name: true },
      extraUnits: { id: true, unitId: true, conversionRate: true, isPurchaseUnit: true, unit: { id: true, name: true } },
    },
    unit: { id: true, name: true, type: true },
  },
  returnLines: {
    id: true,
    returnOrderId: true,
    refOrderLineId: true,
    productId: true,
    productSnapshot: true,
    unitId: true,
    unitSnapshot: true,
    conversionRateAtTime: true,
    unitPrice: true,
    quantity: true,
    subTotal: true,
    totalCost: true,
    costPriceAtTime: true,
    product: { id: true, code: true, name: true },
    unit: { id: true, name: true, type: true },
  },
  incomeExpenses: {
    id: true,
    storeId: true,
    code: true,
    occurredAt: true,
    type: true,
    fundId: true,
    fundSnapshot: true,
    categoryId: true,
    categorySnapshot: true,
    partnerId: true,
    partnerSnapshot: true,
    description: true,
    amount: true,
  },
} as any;

export const OrderRelationsList: FindOptionsRelations<Order> = {
  partner: true,
  shipper: true,
};

export const OrderRelations: FindOptionsRelations<Order> = {
  ...OrderRelationsList,
  completer: true,
  canceler: true,
  refOrder: true,
  lines: { product: { baseUnit: true, extraUnits: { unit: true } }, unit: true },
  returnLines: { product: true, unit: true },
  incomeExpenses: { fund: true, category: true, partner: true },
} as any;

export const OrderRelationSelectsForList: RelationSelectConfig<Order> = {
  partner: ["id", "type", "name", "code", "phone", "taxCode"],
  shipper: ["id", "type", "name", "code", "phone"],
};

export const OrderRelationSelects: RelationSelectConfig<Order> = {
  ...OrderRelationSelectsForList,
  completer: ["id", "code", "name", "username"],
  canceler: ["id", "code", "name", "username"],
};
