#!/usr/bin/env bash

echo "🚀 Auto Validator Generator"
echo "=========================="
echo ""
echo "This tool automatically generates Zod validators from TypeORM entities"
echo "by parsing the source code and extracting @Column decorators."
echo ""
echo "📋 Usage:"
echo "--------"
echo "npm run generate:validators all           # Generate for all entities"
echo "npm run generate:validators <EntityName>  # Generate for specific entity"
echo ""
echo "📁 Examples:"
echo "------------"
echo "npm run generate:validators User          # Generate user.validator.generated.ts"
echo "npm run generate:validators Product       # Generate product.validator.generated.ts"
echo "npm run generate:validators all           # Generate for all entities"
echo ""
echo "✨ Features:"
echo "------------"
echo "• Automatic type detection from TypeORM @Column decorators"
echo "• Support for optional fields (nullable: true or ?)"
echo "• Array type support"
echo "• Enum handling"
echo "• Common validation patterns (email, password, phone, url)"
echo "• Automatic directory creation"
echo "• Skips base entity fields (id, createdAt, updatedAt, deletedAt)"
echo "• Filters out relations (@OneToMany, @ManyToOne, etc.)"
echo ""
echo "📄 Generated files include:"
echo "---------------------------"
echo "• CreateEntitySchema - for creation validation"
echo "• UpdateEntitySchema - for update validation (all fields optional)"
echo "• EntityQuerySchema - for query parameters (page, size, keyword)"
echo "• EntityParamsSchema - for route parameters (id validation)"
echo "• TypeScript types for all schemas"
echo ""
echo "🎯 Example output structure:"
echo "----------------------------"
echo "src/module/user/"
echo "└── user.validator.generated.ts"
echo ""
echo "export const CreateUserSchema = z.object({"
echo "  username: z.string().trim(),"
echo "  email: z.email(),"
echo "  password: z.string().trim().min(6)"
echo "});"
echo ""
echo "Ready to generate validators! 🎉"
