import fs from "node:fs";

const employees = [
  {
    id: 37,
    code: "NV000032",
    email: null,
    name: "Tuấn",
    gender: "male",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "1979-10-30T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 33,
      name: "Công nhân kéo thép hàn lưới",
      level: null,
      description: null,
      position: {
        id: 11,
        name: "Công nhân",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "152143251552",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 36,
        education_level: "THPT",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 71,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 72,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 36,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 36,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 36,
    code: "NV000031",
    email: null,
    name: "Hường",
    gender: "female",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "1975-08-17T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 22,
      name: "Trưởng tổ hàn lưới thép",
      level: null,
      description: null,
      position: {
        id: 12,
        name: "Tổ trưởng",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "182241331552",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 35,
        education_level: "THPT",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 69,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 70,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 35,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 35,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 35,
    code: "NV000030",
    email: null,
    name: "Huyền",
    gender: "female",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "1985-05-17T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 26,
      name: "TP kế toán",
      level: null,
      description: null,
      position: {
        id: 7,
        name: "Trưởng phòng",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "153483154515",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 34,
        education_level: "Đại học",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 67,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 68,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 34,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 34,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 34,
    code: "NV000029",
    email: null,
    name: "Hoàng",
    gender: "male",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "1981-10-08T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 27,
      name: "TP Mua hàng",
      level: null,
      description: null,
      position: {
        id: 7,
        name: "Trưởng phòng",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "247752294774",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 33,
        education_level: "Cao đẳng",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 65,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 66,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 33,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 33,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 33,
    code: "NV000028",
    email: null,
    name: "Hương",
    gender: "female",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "1993-05-07T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 32,
      name: "Nhân viên Bán hàng",
      level: null,
      description: null,
      position: {
        id: 8,
        name: "Nhân viên",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "152411454112",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 32,
        education_level: "Đại học",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 63,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 64,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 32,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 32,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 32,
    code: "NV000027",
    email: null,
    name: "Linh",
    gender: "female",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "1992-10-08T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 28,
      name: "TP Bán hàng",
      level: null,
      description: null,
      position: {
        id: 7,
        name: "Trưởng phòng",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "153441584345",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 31,
        education_level: "Đại học",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 61,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 62,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 31,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 31,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 31,
    code: "NV000026",
    email: null,
    name: "Ngọc",
    gender: "female",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "1994-10-08T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 25,
      name: "Thủ kho",
      level: null,
      description: null,
      position: {
        id: 7,
        name: "Trưởng phòng",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "152315314611",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 30,
        education_level: "THPT",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 59,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 60,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 30,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 30,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 30,
    code: "NV000025",
    email: null,
    name: "Hồng",
    gender: "male",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "1970-05-21T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 23,
      name: "Trưởng ban bảo vệ",
      level: null,
      description: null,
      position: {
        id: 7,
        name: "Trưởng phòng",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "151123323234",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 29,
        education_level: "THPT",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 57,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 58,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 29,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 29,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 29,
    code: "NV000024",
    email: null,
    name: "Thắng",
    gender: "male",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "1981-07-17T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 24,
      name: "Quản đốc",
      level: null,
      description: null,
      position: {
        id: 7,
        name: "Trưởng phòng",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "153424135425",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 28,
        education_level: "THPT",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 55,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 56,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 28,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 28,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 28,
    code: "NV000023",
    email: null,
    name: "Thành",
    gender: "male",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "2025-08-14T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 20,
      name: "Trưởng tổ kéo thép dưới 4.5",
      level: null,
      description: null,
      position: {
        id: 12,
        name: "Tổ trưởng",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "153252424132",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 27,
        education_level: "THPT",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 53,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 54,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 27,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 27,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 27,
    code: "NV000022",
    email: null,
    name: "Đức",
    gender: "male",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "1985-09-10T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 19,
      name: "Trưởng tổ kéo thép 4.5 đến 6",
      level: null,
      description: null,
      position: {
        id: 12,
        name: "Tổ trưởng",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "132432342343",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 26,
        education_level: "THPT",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 51,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 52,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 26,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 26,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 26,
    code: "NV000021",
    email: null,
    name: "Phương",
    gender: "male",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "1998-09-17T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 21,
      name: "Trưởng tổ kéo thép hàn lưới",
      level: null,
      description: null,
      position: {
        id: 12,
        name: "Tổ trưởng",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "133453354644",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 25,
        education_level: "THPT",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 49,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 50,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 25,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 25,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 25,
    code: "NV000020",
    email: null,
    name: "Lan",
    gender: "female",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "2000-03-08T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 30,
      name: "Công nhân hàn lưới thép",
      level: null,
      description: null,
      position: {
        id: 11,
        name: "Công nhân",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "455454545777",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 24,
        education_level: "THPT",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 47,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 48,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 24,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 24,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 24,
    code: "NV000019",
    email: null,
    name: "Thắm",
    gender: "female",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "2024-07-25T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 30,
      name: "Công nhân hàn lưới thép",
      level: null,
      description: null,
      position: {
        id: 11,
        name: "Công nhân",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "454545454545",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 23,
        education_level: "THPT",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 45,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 46,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 23,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 23,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
  {
    id: 23,
    code: "NV000018",
    email: null,
    name: "Nam",
    gender: "male",
    marital_status: null,
    working_status: null,
    employee_status: null,
    date_of_birth: "1981-10-09T00:00:00.000Z",
    phone: null,
    tax: null,
    ethnicity: null,
    religion: null,
    attendance_code: null,
    description: null,
    avatar: null,
    base_salary: null,
    bank: null,
    bank_branch: null,
    bank_code: null,
    job_position: {
      id: 18,
      name: "Trưởng đội vận chuyển",
      level: null,
      description: null,
      position: {
        id: 7,
        name: "Trưởng phòng",
        level: null,
        description: null,
      },
      organization: {
        id: 2,
        name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
        code: "TC000001",
        responsibility: null,
        establishment: "Thành lập năm 2017",
        industry: null,
        logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
        type: "company",
        files: [],
        address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
        phone: "0983381117",
        hotline: null,
        email: null,
        website: null,
        tax_code: null,
        parent_id: 1,
        production_step_id: null,
        leader_id: null,
        rating: 0,
      },
    },
    identity_code: "133445214265",
    identity_issued_place: null,
    identity_issued_date: null,
    identity_expired_date: null,
    passport_code: null,
    passport_issued_place: null,
    passport_issued_date: null,
    trial_date: null,
    official_date: null,
    educations: [
      {
        id: 22,
        education_level: "THPT",
        training_level: null,
        graduated_place: null,
        faculty: null,
        major: null,
        graduation_year: null,
        files: [],
      },
    ],
    employee_finances: [],
    addresses: [
      {
        id: 43,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: "tt",
      },
      {
        id: 44,
        country: "Việt Nam",
        province: null,
        district: null,
        ward: null,
        details: null,
        type: null,
      },
    ],
    emergency_contacts: [
      {
        id: 22,
        name: null,
        email: null,
        relationship: null,
        address: null,
        phone: null,
      },
    ],
    employee_contracts: [],
    insurances: [
      {
        id: 22,
        is_participating: false,
        rate: null,
        insurance_number: null,
        insurance_salary: null,
        start_date: null,
      },
    ],
    total_capital: 0,
  },
];

function formatDate(value: string | null | undefined) {
  if (!value) return "";

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return "";
  }

  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();

  return `${day}/${month}/${year}`;
}

function getGender(value: string | null | undefined) {
  switch (value) {
    case "male":
      return "Nam";
    case "female":
      return "Nữ";
    default:
      return "";
  }
}

function getAddress(address: any) {
  if (!address) return "";

  return [
    address.details,
    address.ward,
    address.district,
    address.province,
    address.country,
  ]
    .filter(Boolean)
    .join(", ");
}

function mapEmployee(employee: any) {
  const permanentAddress = employee.addresses?.find(
    (x: any) => x.type === "tt",
  );

  const currentAddress = employee.addresses?.find((x: any) => x.type !== "tt");

  const emergency = employee.emergency_contacts?.[0];
  const insurance = employee.insurances?.[0];

  return [
    employee.code ?? "",
    employee.name ?? "",
    getGender(employee.gender),
    formatDate(employee.date_of_birth),
    employee.marital_status ?? "",
    employee.tax ?? "",
    employee.ethnicity ?? "",
    employee.religion ?? "",

    // Định danh
    "CCCD",
    employee.identity_code ?? "",
    formatDate(employee.identity_issued_date),
    employee.identity_issued_place ?? "",
    formatDate(employee.identity_expired_date),

    // Liên hệ
    employee.email ?? "",
    employee.phone ?? "",

    // Địa chỉ
    getAddress(permanentAddress),
    getAddress(currentAddress),

    // Khẩn cấp
    emergency?.name ?? "",
    emergency?.phone ?? "",
    emergency?.relationship ?? "",

    // Công việc
    employee.job_position?.organization?.name ?? "",
    employee.job_position?.position?.name ?? "",
    employee.base_salary ?? "",
    employee.working_status ?? "",
    employee.employee_status ?? "",
    formatDate(employee.trial_date),
    formatDate(employee.official_date),

    // Ngân hàng
    employee.bank ?? "",
    employee.bank_code ?? "",

    // Bảo hiểm
    insurance?.insurance_number ?? "",
    formatDate(insurance?.start_date),
    insurance?.rate ?? "",

    // Ghi chú
    employee.description ?? "",
  ];
}

function printEmployeesForExcel(employees: any[]) {
  // =========================================================
  // SHEET 1: NHÂN VIÊN
  // =========================================================

  const employeeGroupHeaders = [
    "THÔNG TIN CÁ NHÂN",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "THÔNG TIN ĐỊNH DANH",
    "",
    "",
    "",
    "",
    "THÔNG TIN LIÊN HỆ",
    "",
    "ĐỊA CHỈ",
    "",
    "LIÊN HỆ KHẨN CẤP",
    "",
    "",
    "CÔNG VIỆC",
    "",
    "",
    "",
    "",
    "",
    "NGÂN HÀNG",
    "",
    "BẢO HIỂM",
    "",
    "",
    "GHI CHÚ",
  ];

  const employeeHeaders = [
    "Mã nhân viên (*)",
    "Tên nhân viên (*)",
    "Giới tính",
    "Ngày sinh",
    "Tình trạng hôn nhân",
    "Mã số thuế cá nhân",
    "Dân tộc",
    "Tôn giáo",
    "Loại giấy tờ",
    "Số CCCD/CMND/HC",
    "Ngày cấp",
    "Nơi cấp",
    "Ngày hết hạn",
    "Email",
    "SĐT",
    "Địa chỉ thường trú",
    "Nơi ở hiện tại",
    "Họ tên",
    "SĐT",
    "Quan hệ",
    "Đơn vị công tác",
    "Vị trí công việc",
    "Lương cơ bản",
    "Tình trạng làm việc",
    "Trạng thái NV",
    "Ngày thử việc",
    "Ngày chính thức",
    "Ngân hàng",
    "Số tài khoản",
    "Số sổ BHXH",
    "Ngày bắt đầu",
    "Tỷ lệ đóng (%)",
    "Ghi chú",
  ];

  const employeeRows = employees.map(mapEmployee);

  const employeeText = [
    employeeGroupHeaders.join("\t"),
    employeeHeaders.join("\t"),
    ...employeeRows.map((row) => row.join("\t")),
  ].join("\n");

  // =========================================================
  // SHEET 2: PHỤ CẤP
  // =========================================================

  const allowanceHeaders = [
    "Mã nhân viên (*)",
    "Tên phụ cấp (*)",
    "Số tiền",
    "Ghi chú",
  ];

  const allowanceRows = employees.flatMap((employee) =>
    (employee.employee_finances ?? [])
      .filter((finance: any) => finance.type === "allowance")
      .map((finance: any) => [
        employee.code ?? "",
        finance.name ?? "",
        finance.amount ?? "",
        finance.note ?? "",
      ]),
  );

  const allowanceText = [
    allowanceHeaders.join("\t"),
    ...allowanceRows.map((row) => row.join("\t")),
  ].join("\n");

  // =========================================================
  // SHEET 3: KHẤU TRỪ
  // =========================================================

  const deductionHeaders = [
    "Mã nhân viên (*)",
    "Tên khấu trừ (*)",
    "Số tiền",
    "Ghi chú",
  ];

  const deductionRows = employees.flatMap((employee) =>
    (employee.employee_finances ?? [])
      .filter((finance: any) => finance.type === "deduction")
      .map((finance: any) => [
        employee.code ?? "",
        finance.name ?? "",
        finance.amount ?? "",
        finance.note ?? "",
      ]),
  );

  const deductionText = [
    deductionHeaders.join("\t"),
    ...deductionRows.map((row) => row.join("\t")),
  ].join("\n");

  // =========================================================
  // SHEET 4: HỢP ĐỒNG
  // =========================================================

  const contractHeaders = [
    "Mã nhân viên (*)",
    "Số hợp đồng (*)",
    "Loại hợp đồng",
    "Lương hợp đồng",
    "Ngày bắt đầu",
    "Ngày kết thúc",
  ];

  const contractRows = employees.flatMap((employee) =>
    (employee.employee_contracts ?? []).map((contract: any) => [
      employee.code ?? "",
      contract.code ?? "",
      contract.type ?? "",
      contract.salary ?? "",
      formatDate(contract.start_date),
      formatDate(contract.end_date),
    ]),
  );

  const contractText = [
    contractHeaders.join("\t"),
    ...contractRows.map((row) => row.join("\t")),
  ].join("\n");

  return {
    employees: employeeText,
    allowances: allowanceText,
    deductions: deductionText,
    contracts: contractText,
  };
}

// =========================================================
// EXPORT
// =========================================================

const result = printEmployeesForExcel(employees);

fs.writeFileSync("seeds/employees.tsv", result.employees, "utf8");

fs.writeFileSync("seeds/employee-allowances.tsv", result.allowances, "utf8");

fs.writeFileSync("seeds/employee-deductions.tsv", result.deductions, "utf8");

fs.writeFileSync("seeds/employee-contracts.tsv", result.contracts, "utf8");

console.log("Đã xuất thành công:");
console.log("- employees.tsv");
console.log("- employee-allowances.tsv");
console.log("- employee-deductions.tsv");
console.log("- employee-contracts.tsv");
