import fs from "node:fs";
const jobPositions = [
  {
    id: 33,
    name: "Công nhân kéo thép hàn lưới",
    level: null,
    description: null,
    position: {
      id: 11,
      name: "Công nhân",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 32,
    name: "Nhân viên Bán hàng",
    level: null,
    description: null,
    position: {
      id: 8,
      name: "Nhân viên",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 31,
    name: "Công nhân kéo thép hàn lưới",
    level: null,
    description: null,
    position: {
      id: 11,
      name: "Công nhân",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 30,
    name: "Công nhân hàn lưới thép",
    level: null,
    description: null,
    position: {
      id: 11,
      name: "Công nhân",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 29,
    name: "GĐ Điều hành",
    level: null,
    description: null,
    position: {
      id: 9,
      name: "Giám đốc",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 28,
    name: "TP Bán hàng",
    level: null,
    description: null,
    position: {
      id: 7,
      name: "Trưởng phòng",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 27,
    name: "TP Mua hàng",
    level: null,
    description: null,
    position: {
      id: 7,
      name: "Trưởng phòng",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 26,
    name: "TP kế toán",
    level: null,
    description: null,
    position: {
      id: 7,
      name: "Trưởng phòng",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 25,
    name: "Thủ kho",
    level: null,
    description: null,
    position: {
      id: 7,
      name: "Trưởng phòng",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 24,
    name: "Quản đốc",
    level: null,
    description: null,
    position: {
      id: 7,
      name: "Trưởng phòng",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 23,
    name: "Trưởng ban bảo vệ",
    level: null,
    description: null,
    position: {
      id: 7,
      name: "Trưởng phòng",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 22,
    name: "Trưởng tổ hàn lưới thép",
    level: null,
    description: null,
    position: {
      id: 12,
      name: "Tổ trưởng",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 21,
    name: "Trưởng tổ kéo thép hàn lưới",
    level: null,
    description: null,
    position: {
      id: 12,
      name: "Tổ trưởng",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 20,
    name: "Trưởng tổ kéo thép dưới 4.5",
    level: null,
    description: null,
    position: {
      id: 12,
      name: "Tổ trưởng",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 19,
    name: "Trưởng tổ kéo thép 4.5 đến 6",
    level: null,
    description: null,
    position: {
      id: 12,
      name: "Tổ trưởng",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
  {
    id: 18,
    name: "Trưởng đội vận chuyển",
    level: null,
    description: null,
    position: {
      id: 7,
      name: "Trưởng phòng",
      level: null,
      description: null,
    },
    organization: {
      id: 2,
      name: "CÔNG TY CỔ PHẦN AMAXTEC VIỆT NAM",
      code: "TC000001",
      responsibility: null,
      establishment: "Thành lập năm 2017",
      industry: null,
      logo: "/uploads/logo amaxtec 5-1760667572450.JPG",
      type: "company",
      files: [],
      address: "Cụm CN ô tô Nguyên Khê - xã Thư Lâm - Hà Nội",
      phone: "0983381117",
      hotline: null,
      email: null,
      website: null,
      tax_code: null,
      parent_id: 1,
      production_step_id: null,
      leader_id: null,
      rating: 0,
    },
  },
];
function printJobPositionsForExcel(jobPositions: any[]) {
  const headers = ["Tên vị trí (*)", "Cấp bậc", "Chức danh", "Ghi chú"];

  const text = [
    headers.join("\t"),
    ...jobPositions.map((jobPosition) =>
      [
        jobPosition.name ?? "",
        jobPosition.level ?? "",
        jobPosition.position?.name ?? "",
        jobPosition.description ?? "",
      ].join("\t"),
    ),
  ].join("\n");

  return text;
}

const text = printJobPositionsForExcel(jobPositions);

fs.writeFileSync("seeds/job-positions.tsv", text, "utf8");

console.log("Đã xuất seeds/job-positions.tsv");
